* TODO Rb Control System
Add devices, device drivers and gui devices
- [ ] AOM Driver (Grace did this)
  - [ ] GUI Device
- [ ] CAEN Power supply (Grace did this)
  - [ ] GUI Device
- [ ] Current Supplies? (BKPrecision drivers work here)
  - [ ] GUI Device (BKPrecision Supplies??)

* TODO Documentation for Shutter Box
:PROPERTIES:
:ID:       B383DA13-3FAA-4CF1-861E-F317C1690AE8
:END:
* INPROG Assemble Shutter Box
:PROPERTIES:
:ID:       235BC5EC-1440-4387-BF40-665CE765EA71
:END:
Run power from 5V
Power switch off of same power from box.
Run forward bias diode from Relay "DC+" to + side of the all the switches. Run other side of all the diodes to the + side of the isolating bnc port. Run the ground side of the isolating bnc to DC- on the relay. Run reverse bias diode from ground of isolating bnc to other side of isolating bnc.

Solder small wires from isolating bnc on switch mount to switch in mount.

Solder non-isolating BNCs ground together. Run wire from there to XM on relay.

Circuit Stuff
1. [ ] Cut wire
   1. [ ] 4 short wire to connect + side of all the switches
   2. [ ] 4 long green wire to connect ground of all switches (off of isolating bnc)
   3. [ ] 4 long red wire for nonisolating bnc
   4. [ ] 4 long green wire for nonisolating bnc
   5. [ ] 4 short green wire to connect ground of all relay channels
2. [ ] Solder BNC panel mounts
3. [ ] Solder wire together
   1. [ ] solder 4 green wires from nonisolating BNC together to connect ground of all the switches.
   2. [ ] solder
4. [ ] Diodes
   1. [ ] Solder reverse bias diode from switch output to isolating BNC ground for each switch.
   2. [ ] Add forward bias diode from banana connector to DC+
5. [ ] Assembly

Assembly of Box      
* NEXT Ask Mohit about current supplies

* INPROG DeMille Lab onboarding                                :uchicago:lab:
:PROPERTIES:
:ID:       059F06A4-E43B-4970-AD88-5475D42E2935
:END:

* NEXT Machine Shop Training Paper work                                 :lab:
SCHEDULED: <2025-01-08 Wed>
:PROPERTIES:
:ADDED: [2024-11-18]
:END:
In email from Pranav
* INPROG Quantum Dynamics Notes + Readings                     :uchicago:lab:
DEADLINE: <2025-01-06 Mon>
:PROPERTIES:
:ADDED: [2024-12-03]
:END:

* NEXT [#F] MCAW Recap
Do this at some point
